### ISSUE TITLE
raw file links point to bound gateway instead of effective gateway

### ISSUE THREAD

**Issue by compleatang** [ipfs/webui#3]
context: we have an IPFS gateway on a server. gateway is bound to `0.0.0.0:8080`. in front of gateway, nginx is reverse proxying `8080` to `443`. that all works fine. in addition, the API port is bound to `0.0.0.0:5001`. 

when i go to the webui [here](http://54.93.113.247:5001/ipfs/QmaaqrHyAQm7gALkRW8DcfGX3u8q9rWKnxEMmf7m9z515w/#/files) and hover on links to the raw files they resolve to `http://0.0.0.0:8080/ipfs/....` rather than our gateway. 

if there was a way to pass an effective base URL to the webui for links that would be tremendous, or some other way to have the ui understand that our public facing gateway is running on a different URL than what the backend is bound to.

Great work, BTW, the UI looks fantastic.

**Comment by travisperson** [comment]
That definitely sounds like bug. It should at the very least resolve to the public facing gateway and not `0.0.0.0`

**Comment by travisperson** [comment]
I would like to talk about this issue a bit more.

If the gateway is set to `0.0.0.0` we really don't know what address it is bound too. With this we could at least pull the port from the multiaddr and use it on the hostname of the webui.

There is no good way to map `5000 => 443` from ipfs itself. Maybe this should be a new configuration  option that the webui could ask for.

We could also allow a way to set some options in the webui and store them in localstorage. You could then override which host it will link too.

**Comment by whyrusleeping** [comment]
cant you tell the server IP from some http header?

**Comment by travisperson** [comment]
The simple solution is to just pull use the port from the gateway and combine it with `window.location.host`. This will work for most people.

There are a few weird cases that this doesn't work, but really there isn't a good way to solve it either way besides along it be a configuration.

I think though in those strange cases most people will be explicitly setting a address to bind too instead of using either `127.0.0.1` or `0.0.0.0`.

If the gateway address is `0.0.0.0` we can assume that it will be accessible from the same address as the API. However, if the gateway is set to 127.0.0.1 and has a reverse proxy setup we have no way of knowing which it's setup on.

Like I said I can do the quick fix, but later down the road we may find more issues with this that will need to be solved. Maybe we should just let those get filled when someone comes across them though.

**Comment by jbenet** [comment]
I'd like to fix this soon too. @travisperson next steps here?
