### ISSUE TITLE
Links de-duplicating

### ISSUE THREAD

**Issue by apiarian** [ipfs/webui#412]
I used [this script](https://gist.github.com/apiarian/69eb78a0be5fa93d68a99f7e98a4b0b0) to create a pair of IPFS objects, a head and a tail, with 2 links pointing from the head to the tail. The links have different names. `ipfs object get $HEAD` shows both of the links in place. But looking at the same object in the DAG view of the webui shows only the first link. The twin-pointer-head can be found at `/ipfs/QmfYhWKZBouVU7GDzVxEG6gLetESNStsdD63KT8jUe23eV` or by running that script locally.

**Comment by diasdavid** [comment]
Hi @apiarian! Seems that it has been a while since you asked this question, apologies for that.

The reason why you aren't able to get a linked list is that data structs in IPFS are [DAGs](https://en.wikipedia.org/wiki/Directed_acyclic_graph).

If you still have questions related to how this works, consider opening an issue at our discussion forum https://discuss.ipfs.io/

Thanks!
